<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13027" started-at="2019-05-22T09:17:52Z" finished-at="2019-05-22T09:18:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13027" started-at="2019-05-22T09:17:52Z" finished-at="2019-05-22T09:18:05Z">
      <class name="Ultimatix_Def.Ultimatix_Def">
        <test-method status="FAIL" signature="dash_board_is_displayed()[pri:0, instance:Ultimatix_Def.Ultimatix_Def@5bcab519]" name="dash_board_is_displayed" duration-ms="23" started-at="2019-05-22T09:17:52Z" finished-at="2019-05-22T09:17:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.interactions.Actions.<init>(Actions.java:44)
at Ultimatix_Def.Ultimatix_Def.dash_board_is_displayed(Ultimatix_Def.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dash_board_is_displayed -->
        <test-method status="FAIL" signature="sign_on_is_clicked()[pri:0, instance:Ultimatix_Def.Ultimatix_Def@5bcab519]" name="sign_on_is_clicked" duration-ms="11" started-at="2019-05-22T09:17:52Z" finished-at="2019-05-22T09:17:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at Ultimatix_Def.Ultimatix_Def.sign_on_is_clicked(Ultimatix_Def.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sign_on_is_clicked -->
        <test-method status="PASS" signature="the_URL_is_launched()[pri:0, instance:Ultimatix_Def.Ultimatix_Def@5bcab519]" name="the_URL_is_launched" duration-ms="12373" started-at="2019-05-22T09:17:52Z" finished-at="2019-05-22T09:18:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- the_URL_is_launched -->
        <test-method status="PASS" signature="the_UserID_and_PWD_are_entered()[pri:0, instance:Ultimatix_Def.Ultimatix_Def@5bcab519]" name="the_UserID_and_PWD_are_entered" duration-ms="520" started-at="2019-05-22T09:18:04Z" finished-at="2019-05-22T09:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- the_UserID_and_PWD_are_entered -->
      </class> <!-- Ultimatix_Def.Ultimatix_Def -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
